heat_template_version: 2013-05-23
description: >
  A simple Heat template that spins up multiple instances and a private network (HOT template in YAML).

 
parameters:
 image:
    type: string
    label: Image Name
    description: Image to be used for compute instance
    default: trusty-server-cloudimg-amd64-disk1.2015-01-27
 
resources:
  heat_network_01:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: heat-network-01
  heat_subnet_01:
    type: OS::Neutron::Subnet
    properties:
      name: heat-subnet-01
      cidr: 10.10.10.0/24
      enable_dhcp: true
      network_id: { get_resource: heat_network_01 }
      dns_nameservers: [8.8.8.8]
  heat_router_01:
    type: OS::Neutron::Router
    properties:
      admin_state_up: true
      name: heat-router-01
  heat_router_01_gw:
    type: OS::Neutron::RouterGateway
    properties:
      network_id: 68976754-2af4-42f5-b7d0-442970634987
      router_id: { get_resource: heat_router_01 }
  heat_router_int0:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: heat_router_01 }
      subnet_id: { get_resource: heat_subnet_01 }

  webapp_port:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_resource: heat_network_01 }
  webapp_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: 68976754-2af4-42f5-b7d0-442970634987
      port_id: { get_resource: webapp_port }

  web-app-instance:
    type: OS::Nova::Server
    properties:
      name: web-app-instance
      image: { get_param: image }
      flavor: Micro-Small
      networks:
        - port: { get_resource: webapp_port }
      user_data: |
            #!/bin/bash

            sudo -i
            apt-get update
            apt-get install apache2 -y
            apt-get install git -y

            cd /root
            git clone https://github.com/cloudpractice/reveal.js.git
            git clone https://github.com/cloudpractice/WeatherApp.git
            mv reveal.js/* /var/www/html
            mkdir /var/www/html/weather
            mv WeatherApp/src/* /var/www/html/weather